name: 'Setup'
description: 'Setup node, install deps, compile'
runs:
    using: 'composite'
    steps:
        - uses: actions/setup-node@v4.3.0
          with:
              node-version: '22'
              cache: 'npm'

        - name: Install dependencies
          shell: bash
          run: npm ci

        - name: Build project
          shell: bash
          run: npm run compile
