name: 'Setup'
description: 'Checkout repository, setup node, install deps, build'
runs:
    using: 'composite'
    steps:
        - name: Cache turbo build output
          uses: actions/cache@v4.2.3
          with:
              path: .turbo
              key: '${{ runner.os }}-turbo-${{ github.sha }}'
              restore-keys: |
                  ${{ runner.os }}-turbo-

        - name: Install pnpm
          uses: pnpm/action-setup@v4.1.0
          with:
              version: 10.12.1

        - name: Setup
          uses: actions/setup-node@v4.3.0
          with:
              node-version: 22.17.0
              registry-url: 'https://registry.npmjs.org'
              cache: 'pnpm'

        - name: Install deps
          shell: bash
          run: pnpm install --frozen-lockfile

        - name: Build
          shell: bash
          run: pnpm run build
