packages:
  - examples/**/*
  - packages/**/*

onlyBuiltDependencies:
  - '@splunk/otel'
  - '@swc/core'
  - core-js
  - electron
  - electron-winstaller
  - esbuild
  - fs-xattr
  - macos-alias
  - protobufjs
  - sharp
