import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.grid}>
          <Link href="/list">
            <a className={styles.card}>
              <h2>List &rarr;</h2>
              <p>Example with fetch & API.</p>
            </a>
          </Link>
          <Link href="/static-props">
            <a className={styles.card}>
              <h2>Static Props &rarr;</h2>
              <p>Server request & SSR</p>
            </a>
          </Link>
          <Link href="/server-side-props">
            <a className={styles.card}>
              <h2>Server Side Props &rarr;</h2>
              <p>Server request, fancier links</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
