/**
 *
 * Copyright 2020-2026 Splunk Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

import { getPackageRoots } from './utils/index.mjs'

const packageJsonRootPath = path.resolve(process.cwd(), 'package.json')
const requestedVersion = process.argv[2]
const semanticVersionPattern =
	/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$/
const packageRoots = getPackageRoots()

if (process.env.npm_lifecycle_event === 'version:bump' && requestedVersion === undefined) {
	throw new Error('Usage: pnpm version:bump <version>')
}

if (requestedVersion !== undefined) {
	if (!semanticVersionPattern.test(requestedVersion)) {
		throw new Error(`Invalid semantic version: ${requestedVersion}`)
	}

	const packagePaths = [process.cwd(), ...packageRoots]
	packagePaths.forEach((packagePath) => {
		const packageJsonPath = path.resolve(packagePath, 'package.json')
		const packageJsonValue = JSON.parse(readFileSync(packageJsonPath, 'utf8'))
		packageJsonValue.version = requestedVersion
		writeFileSync(packageJsonPath, `${JSON.stringify(packageJsonValue, null, '\t')}\n`)
	})
}

const packageJsonRootValue = JSON.parse(readFileSync(packageJsonRootPath, 'utf8'))

packageRoots.forEach((packagePath) => {
	const content = `/**
 *
 * Copyright 2020-${new Date().getFullYear()} Splunk Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

// this is an autogenerated file, see scripts/version-update.mts
export const VERSION = '${packageJsonRootValue.version}'
`

	const fileUrl = path.resolve(packagePath, 'src', 'version.ts')
	writeFileSync(fileUrl, content)
})
