name: Check Links

on:
    push:
        branches: [main]
    pull_request:

jobs:
    linkChecker:
        name: Link Checker
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #7.0.1

            - name: Link Checker
              uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 #2.9.0
              with:
                  fail: true
                  args: "--verbose --no-progress './**/*.md' './**/*.html' --user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36'"
