name: Check Links

on:
    push:
        branches: [main]
    pull_request:

jobs:
    linkChecker:
        name: Link Checker
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2

            - name: Link Checker
              uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 #2.8.0
              with:
                  fail: true
                  args: "--verbose --no-progress './**/*.md' './**/*.html' --user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36'"
