name: Continuous Integration
on:
    pull_request:
        types: [opened, synchronize]
    push:
        branches: [main]
        tags: [v*]

permissions: read-all

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        permissions: read-all
        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2

            - name: Setup
              uses: ./.github/actions/setup

            - run: pnpm run version:check

            - name: Size check
              run: npm run size-limit

            - name: Lint code
              run: pnpm run lint

            - name: Lint docs
              run: pnpm run lint:markdown

    unit-tests:
        name: Unit Tests
        uses: ./.github/workflows/tests-unit.yml
        secrets: inherit

    integration-tests:
        name: Integration Tests
        uses: ./.github/workflows/tests-integration.yml
        secrets: inherit
